version: '3.8'
services:
  zwave-js-ui:
    image: zwavejs/zwave-js-ui:latest
    container_name: zwave-js-ui
    restart: unless-stopped
    ports:
      - "8091:8091" 
    volumes:
      - ./data/zwave-js-ui:/usr/src/app/store 
    environment:
      - ZWAVEJS_EXTERNAL_CONFIG_DIR=/usr/src/app/store 
    devices:
      - /dev/ttyUSB0:/dev/zwave 
    network_mode: host


  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    ports:
      - "8123:8123" 
    volumes:
      - ./data/homeassistant:/config 
    environment:
      - TZ=Europe/Paris 
    platform: linux/arm/v7 
    networks:
      - zwave_network 

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086" 
    environment:
      - INFLUXDB_DB=home_assistant
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=123456789
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
    networks:
      - zwave_network 

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000" 
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123456789
    volumes:
      - ./data/grafana:/var/lib/grafana 
    networks:
      - zwave_network 

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data 
    networks:
      - zwave_network 

networks:
  zwave_network:
    driver: bridge
   